export enum CATEGORIES {
  THERAPISTS = "THERAPISTS",
  SURGEONS = "SURGEONS",
  OPHTHALMOLOGISTS = "OPHTHALMOLOGISTS",
  DERMATOLOGISTS = "DERMATOLOGISTS",
  CARDIOLOGISTS = "CARDIOLOGISTS",
  DENTISTS = "DENTISTS",
  ORTHOPEDISTS = "ORTHOPEDISTS",
  EXOTOLOGISTS = "EXOTOLOGISTS",
}
